// Generated by scripts/generate-public-guide-routes.cjs from published guide data.
// Keep the analytics bundle small; do not import medical guide bodies here.
export const PUBLIC_SYMPTOM_PATHS = [
  "/symptoms/headache-stiff-neck",
  "/symptoms/stress-insomnia",
  "/symptoms/stomach-fatigue",
  "/symptoms/menstrual-pain-chill",
  "/symptoms/chronic-fatigue-lethargy",
  "/symptoms/lower-back-pain-sciatica",
  "/symptoms/eye-strain-fatigue",
  "/symptoms/constipation-ibs",
  "/symptoms/dizziness-tinnitus",
  "/symptoms/climacteric-hot-flash",
  "/symptoms/allergic-rhinitis-hayfever",
  "/symptoms/knee-joint-pain"
] as const;
export const PUBLIC_CLINICAL_GUIDE_PATHS = [
  "/clinical/symptoms/shoulder",
  "/clinical/symptoms/back",
  "/clinical/symptoms/headache",
  "/clinical/symptoms/sleep",
  "/clinical/symptoms/digestion",
  "/clinical/symptoms/fatigue"
] as const;
